---
- name: Playbook to copy webdriver & modify /etc/hosts
  hosts: all
  become: true
  tasks:
   - name: To copy selenium webdriver to slave node
     copy:
      src: /home/edureka/geckodriver
      dest: /home/edureka

   - name: To make entry in /etc/hosts file
     shell: |
          echo "172.31.26.165 puppetmaster puppet" >> /etc/hosts
          echo "172.31.23.14 puppetclient" >> /etc/hosts
          exit 0


   
